-- CoolShark Docker MySQL 初始化脚本
-- 创建所有数据库
CREATE DATABASE IF NOT EXISTS cs_mall_pms DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS cs_mall_oms DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS cs_mall_ams DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS cs_mall_ums DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS cs_mall_seckill DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS cs_mall_resource DEFAULT CHARSET utf8mb4;
