# ##################################################################### #
#                            【生产】环境配置                              #
# ##################################################################### #
#  当前文件是Profile配置，需要主配置文件中通过spring.profiles.active激活后生效   #
# ##################################################################### #

# 部署到阿里云后，将此地址替换为服务器内网IP或127.0.0.1(单机部署)
my:
  server:
    addr: ${ALIYUN_SERVER_IP:127.0.0.1}

spring:
  application:
    name: mall-search
  jackson:
    default-property-inclusion: always
  cloud:
    nacos:
      discovery:
        server-addr: http://${my.server.addr}:8848
  elasticsearch:
    rest:
      uris: http://${my.server.addr}:9200
  redis:
    host: ${my.server.addr}
    port: 6379
    password: ${REDIS_PASSWORD:}

dubbo:
  application:
    name: mall-search
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://${my.server.addr}:8848
    use-as-config-center: false
    use-as-metadata-center: false
  consumer:
    check: false

knife4j:
  production: true

logging:
  level:
    com.cooxiao.mall: info
