server:
  #10086原来的
  port: 10087
spring:
  main:
    web-application-type: reactive
  profiles:
    active: test

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n"
