-- Database: cs_mall_pms
-- Table: pms_spu

CREATE TABLE `pms_spu` (
  `id` bigint NOT NULL COMMENT 'SPU id',
  `name` varchar(128) NOT NULL COMMENT 'SPU 名称',
  `type_number` varchar(64) NOT NULL COMMENT 'SPU 编号',
  `title` varchar(255) NOT NULL COMMENT '标题',
  `description` text COMMENT '简介',
  `list_price` decimal(10,2) DEFAULT '0.00' COMMENT '价格（显示在列表中）',
  `stock` int DEFAULT '0' COMMENT '当前库存（冗余）',
  `stock_threshold` int DEFAULT '0' COMMENT '库存预警阈值（冗余）',
  `unit` varchar(16) DEFAULT NULL COMMENT '计件单位',
  `brand_id` bigint DEFAULT NULL COMMENT '品牌 id',
  `brand_name` varchar(64) DEFAULT NULL COMMENT '品牌名称（冗余）',
  `category_id` bigint DEFAULT NULL COMMENT '类别 id',
  `category_name` varchar(64) DEFAULT NULL COMMENT '类别名称（冗余）',
  `attribute_template_id` bigint DEFAULT NULL COMMENT '属性模板 id',
  `album_id` bigint DEFAULT NULL COMMENT '相册 id',
  `pictures` text COMMENT '组图 URLs，使用 JSON 数组表示',
  `keywords` text COMMENT '关键词列表，各关键词使用英文的逗号分隔',
  `tags` varchar(255) DEFAULT NULL COMMENT '标签列表，各标签使用英文的逗号分隔，原则上最多 3 个',
  `sales` int DEFAULT '0' COMMENT '销量（冗余）',
  `comment_count` int DEFAULT '0' COMMENT '买家评论数量总和（冗余）',
  `positive_comment_count` int DEFAULT '0' COMMENT '买家好评数量总和（冗余）',
  `sort` int DEFAULT '0' COMMENT '自定义排序序号',
  `is_deleted` int DEFAULT '0' COMMENT '是否标记为删除，1=已删除，0=未删除',
  `is_published` int DEFAULT '0' COMMENT '是否上架（发布），1=已上架，0=未上架',
  `is_new_arrival` int DEFAULT '0' COMMENT '是否新品，1=新品，0=非新品',
  `is_recommend` int DEFAULT '0' COMMENT '是否推荐，1=推荐，0=不推荐',
  `is_checked` int DEFAULT '0' COMMENT '是否已审核，1=已审核，0=未审核',
  `check_user` varchar(64) DEFAULT NULL COMMENT '审核人（冗余）',
  `gmt_check` datetime DEFAULT NULL COMMENT '审核通过时间（冗余）',
  `gmt_create` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据创建时间',
  `gmt_modified` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据最后修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_type_number` (`type_number`),
  KEY `idx_name` (`name`),
  KEY `idx_brand_id` (`brand_id`),
  KEY `idx_category_id` (`category_id`),
  KEY `idx_published` (`is_published`),
  KEY `idx_checked` (`is_checked`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='SPU（Standard Product Unit）表'
